### ISSUE TITLE
Create new logo

### ISSUE THREAD

**Issue by annabajer** [annabajer/atosportosiaramis#1]
Suggested to add here img with logo

header/top.php:

<div class="logo">
    <h1><a href="http://demo.fabthemes.com/edivos/" title="edivos" rel="home">Atos Portos i Aramis</a></h1>
</div>

**Comment by EwelinaSerafin** [comment]
Zrobiłam logo. Potrzebuję, zebys mnie dodała do collaboratorów, żebym mogła zrobić pusha.

**Comment by annabajer** [comment]
Zrobione
